version: '3.8'

services:
  backend:
    container_name: ${PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    image: moodbook_backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m     # JVM 메모리 관리
      - TZ=Asia/Seoul                           # 한국 시간 설정

      # MySQL
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      # ElasticSearch
      - ELASTICSEARCH_URI=${ELASTICSEARCH_URI}

      # Logstash
      - LOG_CONSOLE_PATTERN=${LOG_CONSOLE_PATTERN}

      # MongoDB
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DATABASE=${MONGODB_DATABASE}

      # Redis
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

      # AWS S3
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}

      # JWT
      - JWT_SECRET=${JWT_SECRET}

      # Aladin API
      - ALADIN_API_KEY=${ALADIN_API_KEY}
      - ALADIN_BASE_URL=${ALADIN_BASE_URL}

      # OpenAI
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_URL=${OPENAI_URL}
      - OPENAI_MODEL=${OPENAI_MODEL}
    volumes:
      - /etc/localtime:/etc/localtime:ro      # 한국 시간 설정
      - /home/ubuntu/moodbook/logs:/app/logs
    restart: always