spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dhb6306@gmail.com
    password: fyxjgtwykihautsk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    default: prod  # 기본 실행 프로필 지정

server:
  port: 8080