spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: root
    password: 1234

  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

    batch:
      jdbc:
        initialize-schema: never
      job:
        enabled: false

  sql:
    init:
      mode: never

  data:
    mongodb:
      uri: mongodb+srv://moodbookuser:moodbookpass@moodbookemotion.e9qbkki.mongodb.net/?retryWrites=true&w=majority&appName=MoodBookEmotion
      database: moodbookDB


# AWS S3 적용을 위한 세팅
# S3 사용을 위한 키는 정호종씨에게 문의하세요
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      secret-key: 
      access-key:

aladin:
  api:
    key: ttbzac03281049001
    base-url: https://www.aladin.co.kr/ttb/api/ItemSearch.aspx

jwt:
  secretKey: 12345
DB_NAME: moodbook
