spring:
  profiles:
    default: local  # 기본 실행 프로필 지정

server:
  port: 8080

# AWS S3 적용을 위한 세팅
# S3 사용을 위한 키는 정호종씨에게 문의하세요
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      secret-key:
      access-key: